// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.
//
// Code generated by Microsoft (R) Rust Code Generator.

#![cfg_attr(docsrs, feature(doc_cfg))]

mod generated;
pub use generated::*;
pub mod internal_operation;
pub mod public_operation;
pub mod relative_model_in_operation;
pub mod shared_model_in_operation;

// Pub wrappers for pub(crate) methods so integration tests can call them.
// In a real SDK these would be called by a public convenience layer.

impl internal_operation::clients::AccessInternalOperationClient {
    pub async fn call_internal_decorator_in_internal(&self, name: &str) -> azure_core::Result<()> {
        self.internal_decorator_in_internal(name, None).await?;
        Ok(())
    }

    pub async fn call_no_decorator_in_internal(&self, name: &str) -> azure_core::Result<()> {
        self.no_decorator_in_internal(name, None).await?;
        Ok(())
    }

    pub async fn call_public_decorator_in_internal(&self, name: &str) -> azure_core::Result<()> {
        self.public_decorator_in_internal(name, None).await?;
        Ok(())
    }
}

impl relative_model_in_operation::clients::AccessRelativeModelInOperationClient {
    pub async fn call_discriminator(&self, kind: &str) -> azure_core::Result<()> {
        self.discriminator(kind, None).await?;
        Ok(())
    }

    pub async fn call_operation(&self, name: &str) -> azure_core::Result<()> {
        self.operation(name, None).await?;
        Ok(())
    }
}

impl shared_model_in_operation::clients::AccessSharedModelInOperationClient {
    pub async fn call_internal(&self, name: &str) -> azure_core::Result<()> {
        self.internal(name, None).await?;
        Ok(())
    }
}
