// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.
//
// Code generated by Microsoft (R) Rust Code Generator.

#![cfg_attr(docsrs, feature(doc_cfg))]

mod generated;
pub use generated::*;
pub mod test;

pub mod models {
    pub use crate::generated::models::*;
    use azure_core::time::OffsetDateTime;
    use serde_json::Number;

    pub fn deserialize_base64<'de, D>(deserializer: D) -> Result<Option<Vec<u8>>, D::Error>
    where
        D: serde::Deserializer<'de>,
    {
        let _ = deserializer;
        todo!()
    }

    pub fn deserialize_name<'de, D>(deserializer: D) -> Result<Option<String>, D::Error>
    where
        D: serde::Deserializer<'de>,
    {
        let _ = deserializer;
        todo!()
    }

    pub fn deserialize_safeint<'de, D>(deserializer: D) -> Result<Option<Number>, D::Error>
    where
        D: serde::Deserializer<'de>,
    {
        let _ = deserializer;
        todo!()
    }

    pub fn deserialize_time<'de, D>(deserializer: D) -> Result<Option<OffsetDateTime>, D::Error>
    where
        D: serde::Deserializer<'de>,
    {
        let _ = deserializer;
        todo!()
    }

    pub fn deserialize_times<'de, D>(
        deserializer: D,
    ) -> Result<Option<Vec<OffsetDateTime>>, D::Error>
    where
        D: serde::Deserializer<'de>,
    {
        let _ = deserializer;
        todo!()
    }
}
